version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app
  image: fusion
  container_name: fusion_web 

 mysqldb:
  image: mysql:latest
  ports:
  - 3306:3306
  environment:
  - MYSQL_USER=root  
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  container_name: mysqldb
  restart: always

volumes:
  mysql:
  mysql_config:

